"use client"
import "./globals.css";
import AnimatedCursor from "react-animated-cursor";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from "./Components/Navbar";
import MobileNavbar from "./Components/MobileNavbar";
import useScreenWidth from "@/lib/useScreenWidth";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const screenWidth = useScreenWidth();
  const isMobile = screenWidth < 768; // md breakpoint in Tailwind CSS

  return (
    <html lang="en" className="scroll-smooth">
      <body>
        {!isMobile && (
          <AnimatedCursor
            innerSize="25"
            outerSize="25"
            innerScale={2}
            outerScale={2}
            color="84,114,228"
          />
        )}
        <Theme accentColor="crimson" appearance="light">
          <MobileNavbar />
          <Navbar />
          {children}
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
